### ISSUE TITLE
Travel sensors are undefined

### ISSUE THREAD

**Issue by veleek** [Instagraeme/Home-Assistant-Configuration#8]
There are a whole bunch of sensors defined in `travel.yaml` but they don't appear to be defined anywhere.  E.g.

```
sensor.graeme_to_work
sensor.graeme_to_home
```

I'm assuming this is because there may be some sensitive address info or something like that?  Regardless, it would be nice if the non-private parts of the configuration could me made available to provide examples around how to setup these sorts of sensors on our own.

**Comment by smuggyuk** [comment]
They're defined in Home-Assistant-Configuration/includes/sensors/google_travel_time.yaml

**Comment by veleek** [comment]
Ah okay.  So the sensor entity names are generated automatically from the "Friendly Names" of the sensors.  That explains why I couldn't find them while searching.

`Graeme to Work` -> `sensor.graeme_to_work`

Thanks!

**Comment by Instagraeme** [comment]
Sorry I completely missed this until the emails came in today. Let me know there is anything else I can help with.
